### ISSUE TITLE
compiled against a different Node.js version 

### ISSUE THREAD

**Issue by Tithy** [julianhille/MuhammaraJS#187]
![image](https://user-images.githubusercontent.com/28753993/176172659-da8ce7f1-b0bd-41bc-8fca-ea88d656343b.png)

electron：18.0.3
node: 16.13.2
Please tell me what to do to use?

**Comment by julianhille** [comment]
The issue is you install with npm / yarn and your system (or nvm) version of node.
In this case its 16.x which you got there, but then you start electron which brings its own node version with it which is a bit different.
That's why you see ABI 93 which is any 16.x node version and 103 which is any 18.x electron.

You need to rebuild for your electron version by a "prestart" or "post" build command
I do both in other projects and issue there: `electron-builder install-app-deps` or `npx electron-builder install-app-deps` or what ever you need to call to tell your node package manager to issue that command.

Feel free to get back to me.

Btw. Afterwards you should not be able to require muhammara in node repl anymore and you should get the issue the other way around. It should then tell you its compiled for 103 and not 93.

**Comment by Tithy** [comment]
Thanks, my problem was solved. Nodejs downgraded the project and did not recompile. After removing the node_modules, the recompilation works fine.
I still have a question, can I get a thumbnail? The first time I used this library, I didn't find the relevant API. My English is not very good, please understand.

**Comment by julianhille** [comment]
Im not sure if i understand correctly. What are you trying to do? Are you trying to add a picture to a page?
What kind of thumbnail? Where you want it to be?

Please try to rephrase.

**Comment by Tithy** [comment]
![image](https://user-images.githubusercontent.com/28753993/176217950-b813eaca-1b55-444c-9153-bc2f0ac11f89.png)
I just want to get a small preview of each page of the pdf for display use. Just like the picture shown in the list on the left in the picture. For performance reasons, the original image cannot be used. Or is there another solution?

**Comment by julianhille** [comment]
Ok. So you want to display a preview of an original (bigger) pdf.

1.Muhammara is not capable of generating jpgs from pdfs you might want to use: https://www.npmjs.com/package/pdf-image which does exactly that.

2. if you want to keep it as pdf in the end but the goal is to reduce the size and just preview the file somehow (in a browser or local tool) you could use muhmmara to resize the pages.

Am i getting it right? Does that solve your problem?

**Comment by Tithy** [comment]
Pdf-image should solve my problem. I need jpg. I need a smaller image preview than the pdf original. Thank you
