### ISSUE TITLE
Best way to add watermark to all the pages of PDF

### ISSUE THREAD

**Issue by ladvishal1985** [julianhille/MuhammaraJS#318]
I have PDF files that are downloaded using a signed URL. I would like to add watermark to all the pages of PDF without requiring to write the pdf file to disk and just allow browser to download the file. I referred this example 
https://github.com/julianhille/MuhammaraJS/issues/284
Can we pass byteArray/blob instead of passing the path to read the pdf for modification ?

**Comment by julianhille** [comment]
https://github.com/julianhille/MuhammaraJS/issues/289#issuecomment-1482942617

have a look here this might answer your question if i understand correctly.

In this example the file "originated from a base64 string" instead of a file

let me know if that helps or points you to the solution to your problem, also if i misunderstood.

**Comment by julianhille** [comment]
im sorry i misunderstood. Here is an example to directly write to a response stream: https://github.com/julianhille/MuhammaraJS/blob/develop/samples/PDFServer.js#L10

**Comment by julianhille** [comment]
i close this for now as it seems fixed to me with the samples above. feel free to reopen if you tested it and it does not help you.

thanks
