### ISSUE TITLE
Module cannot be loaded into an signed electron app

### ISSUE THREAD

**Issue by julianlampert** [julianhille/MuhammaraJS#78]
I am using muhammarajs in an electron app. After the application get's signed via electron-builder, I run into the following error.

![image](https://user-images.githubusercontent.com/9407976/111196170-49e52800-85bd-11eb-8619-c2c187e818e1.png)

Could this be the reason for the issue?
Ref: https://github.com/electron-userland/electron-builder/issues/844#issuecomment-255573692

> Ask module author to use prebuild. And set buildDependenciesFromSource to true as workaround.

Would prebuilds fix this issue?
Ref: https://github.com/electron-userland/electron-builder/issues/844#issuecomment-325688077

I was trying to build & sign the windows app within a linux container. (Docker Hub: electronuserland/builder:wine)
Only building (without signing) works as expected.

**Comment by julianhille** [comment]
I'm currently using muhammara in a signed Electron app and it works fine on windows with all released versions,  but we're not building on wine but on a legit windows os.

Can you provide a full build log?
This looks like the binary does not get signed.
You could also try to force npm arch through config. It might download the wrong binary. 
Please use `--verbose` when doing npm or yarn install for the build log. 
You should also set `npm_config_loglevel=silly` as env variable, because node-pre-gyp then logs some more. 

I had a quick look into our package.json and we're not doing anything special. It's packet into asar and there is no special config regarding signing all binaries.

Please also provide a package.json if you can.

**Comment by julianlampert** [comment]
Signing the application within a windows runner is working as expected. Thank you for your help!

Ref.: https://github.com/electron-userland/electron-builder/issues/844#issuecomment-255573692
